### ISSUE TITLE
[Help] Trying to install but...

### ISSUE THREAD

**Issue by Zalatis** [Redball45/Redball-Cogs#40]
I'm just trying to install the guildwars2 cog but my red didn't show me this cog as a valid cog :x

**Comment by Redball45** [comment]
Hey,

Sorry for not noticing until now I don't really check here that often.

If you're just after the guild wars commands you might be better served by just inviting the bot by Maselkov into your server (more info here https://github.com/Maselkov/GW2Bot)

If you want to load it into red however...

First, I'd check which version of red are you trying to install this onto, the master branch is for v2, and redv3 branch for v3.

With both you'll also need to have installed MongoDB (https://www.mongodb.com/download-center#community) and motor (https://pypi.python.org/pypi/motor/) for the cog's database.

If you can post a screenshot what error you're getting I'll see if I can help, my discord is Redball#9401 or I'm in the GW2Bot discord linked above if you want to contact me directly on there instead.
